"use strict";
// Actual Router/SQLite/auth/media acceptance. Input must be the explicitly
// synthetic loopback fixture; never an existing user installation or profile.
const {test}=require("node:test"),assert=require("node:assert/strict"),fs=require("node:fs");
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||"playwright"),{cinemaRealFocusBrowser}=require("./cinema-remote-browser-support.cjs");
test("live Router browser pairing control owner outcomes revocation and local offline pause",{skip:!process.env.CINEMA_REMOTE_LIVE_SEAM},async()=>{
  const fixture=JSON.parse(fs.readFileSync(process.env.CINEMA_REMOTE_LIVE_SEAM)),base=new URL(fixture.base_url);
  assert.equal(fixture.synthetic_only,true);assert.ok(["127.0.0.1","localhost"].includes(base.hostname));assert.ok(fixture.expires_at>Date.now()/1000);
  const nativeTvFocus=process.env.CINEMA_REMOTE_NATIVE_FOCUS==="1";
  const tvRuntime=nativeTvFocus?await cinemaRealFocusBrowser():await (async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE}),context=await browser.newContext();return {context,close:async()=>{await context.close();await browser.close();}};})(),tvContext=tvRuntime.context,phoneBrowser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_EXECUTABLE}),phoneContext=await phoneBrowser.newContext({viewport:{width:390,height:844}});
  const errors=[];let tv,phone,receiverId;
  async function seed(context,token){await context.addInitScript(token=>{localStorage.setItem("plurx_token",token);localStorage.setItem("plurx_layout","classic");},token);}
  async function save(page,id){const checkbox=page.locator("#"+id);await checkbox.check();await checkbox.locator("xpath=ancestor::div[contains(@class,'setcard')]").getByRole("button",{name:"Save",exact:true}).click();}
  async function tvRoute(hash){await tv.evaluate(hash=>{location.hash=hash;},hash);await tv.waitForFunction(hash=>location.hash===hash&&(hash.startsWith("#/item/")?WATCH_ITEM_PAGE?.id===hash.split("/")[2]:document.getElementById("main")?.dataset.phase==="settled"),hash);}
  async function openPair(){await tvRoute("#/settings/developer");await tv.bringToFront();await tv.waitForFunction(()=>CINEMA_WEB_RECEIVER?.state==="available");await tv.getByRole("button",{name:"Show pairing code",exact:true}).click();await tv.waitForFunction(()=>CINEMA_WEB_RECEIVER?.challenge,null,{timeout:5000}).catch(async error=>{console.log("show code",await tv.evaluate(()=>({state:CINEMA_WEB_RECEIVER?.state,focused:document.hasFocus(),target:!!CINEMA_WEB_RECEIVER?.target,dialog:!!CINEMA_PAIR_DIALOG,status:document.getElementById("cinema-pair-status")?.textContent})));throw error;});return tv.evaluate(()=>CINEMA_WEB_RECEIVER.challenge.code);}
  async function chooseAndClaim(code){await phone.goto(fixture.base_url+"/#/remote");await phone.getByRole("button",{name:"B05 TV",exact:true}).click();await phone.locator("#cinema-phone-code").fill(code);await phone.getByRole("button",{name:"Pair",exact:true}).click();await tv.getByRole("button",{name:"Approve",exact:true}).waitFor({timeout:5000}).catch(async error=>{console.log("pair wait",await phone.evaluate(()=>({message:CINEMA_PAIR_FLOW?.message,pending:!!CINEMA_PAIR_FLOW?.pending,screen:CINEMA_REMOTE_SELECTED?.name})),await tv.evaluate(()=>({receiver:CINEMA_WEB_RECEIVER?.state,focus:document.hasFocus(),pairings:CINEMA_WEB_RECEIVER?.pairings.length,challenge:!!CINEMA_WEB_RECEIVER?.challenge})));throw error;});}
  try{
    await seed(tvContext,fixture.tv_token);await seed(phoneContext,fixture.phone_token);await phoneContext.addInitScript(()=>document.addEventListener("DOMContentLoaded",()=>{globalThis.b05UiTrace=[];const changed=cinemaRemoteUiChanged;cinemaRemoteUiChanged=function(){const c=CINEMA_WEB_CONTROLLER;if(c){b05UiTrace.push({message:c.message,generation:c.generation,acquired:c.acquiredGeneration,revision:c.responseRevision,control:!!c.control,own:c.control?.active_grant_id===c.grant?.grant_id,route:c.state?.route||null});if(b05UiTrace.length>64)b05UiTrace.shift();}return changed();};}));tv=await tvContext.newPage();phone=await phoneContext.newPage();for(const page of [tv,phone])page.on("pageerror",error=>errors.push(error.message));
    await tv.goto(fixture.base_url+"/#/settings/developer");await tv.bringToFront();await tv.locator("#cinema-screen-name").fill("B05 TV");await tv.getByRole("button",{name:"Register this screen",exact:true}).click();await tv.waitForFunction(()=>cinemaRemoteLoad(cinemaRemoteIdentity()).receiver);receiverId=await tv.evaluate(()=>cinemaRemoteLoad(cinemaRemoteIdentity()).receiver.receiver_id);await save(tv,"dev-cinema-receiver");await tv.waitForFunction(()=>CINEMA_WEB_RECEIVER?.state==="available");
    await tv.screenshot({path:"/private/tmp/cinema-b05-developer.png",fullPage:true});await phone.goto(fixture.base_url+"/#/settings/developer");await save(phone,"dev-cinema-companion");
    // Close after claiming, then approve physically: late approval cannot open
    // a retired selection or save its one-time grant on the phone.
    let code=await openPair();await chooseAndClaim(code);await phone.getByRole("button",{name:"Close",exact:true}).click();await tv.getByRole("button",{name:"Approve",exact:true}).click();await phone.waitForTimeout(300);assert.equal(await phone.evaluate(()=>cinemaRemoteLoad(cinemaRemoteIdentity()).grants.length),0);assert.equal(await phone.locator("#cinema-remote-controls").textContent(),"");
    await tv.getByRole("button",{name:"Close",exact:true}).click();code=await openPair();assert.equal(code.length,8);assert.equal(await tv.evaluate(()=>CinemaRemote.dispatch({type:"select"},{...CinemaRemote.snapshot(),source:"network"})),"restricted_surface");assert.equal(await tv.locator("#cinema-pair-qr").count(),1);await chooseAndClaim(code);await tv.screenshot({path:"/private/tmp/cinema-b05-pairing.png",fullPage:true});await tv.getByRole("button",{name:"Approve",exact:true}).click();await phone.getByRole("button",{name:"Use as remote",exact:true}).waitFor();assert.equal(await phone.evaluate(()=>CINEMA_WEB_CONTROLLER.ownsControl()),false);await tv.getByRole("button",{name:"Close",exact:true}).click();await phone.getByRole("button",{name:"Use as remote",exact:true}).click();await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER?.ownsControl(),null,{timeout:5000}).catch(async error=>{console.log("acquire",await phone.evaluate(()=>({message:CINEMA_WEB_CONTROLLER?.message,route:CINEMA_WEB_CONTROLLER?.state?.route,owned:CINEMA_WEB_CONTROLLER?.ownsControl(),generation:CINEMA_WEB_CONTROLLER?.generation,acquired:CINEMA_WEB_CONTROLLER?.acquiredGeneration})),await tv.evaluate(()=>({state:CINEMA_WEB_RECEIVER?.state,focused:document.hasFocus()})),errors);throw error;});
    await tvRoute("#/item/"+fixture.item_id);await tv.waitForFunction(()=>WATCH_ITEM_PAGE?.playable);await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER.state?.route==="details"&&CINEMA_WEB_CONTROLLER.state.credits.length>0,null,{timeout:5000}).catch(async error=>{console.log("details",await tv.evaluate(()=>({receiver:CINEMA_WEB_RECEIVER?.state,focus:document.hasFocus(),route:cinemaRemoteSafeState().route,capabilities:cinemaRemoteSafeState().capabilities,summary:cinemaRemoteSafeState().playback})),await phone.evaluate(()=>({message:CINEMA_WEB_CONTROLLER?.message,route:CINEMA_WEB_CONTROLLER?.state?.route,owned:CINEMA_WEB_CONTROLLER?.ownsControl()})),errors);throw error;});await phone.getByRole("button",{name:"Play this item",exact:true}).click();await tv.waitForFunction(()=>PLAYER?.started&&document.getElementById("video")?.readyState>=2&&!document.getElementById("video").paused);await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER.state?.route==="playback"&&CINEMA_WEB_CONTROLLER.state.credits.length>0);await phone.getByRole("button",{name:"Pause",exact:true}).click();await tv.waitForFunction(()=>document.getElementById("video").paused);await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER.message==="applied");await phone.evaluate(()=>window.scrollTo(0,0));await phone.screenshot({path:"/private/tmp/cinema-b05-phone-viewport.png"});await phone.screenshot({path:"/private/tmp/cinema-b05-phone.png",fullPage:true});const primary=await phone.locator(".cinema-dpad,[data-remote-cap=\"set_playing\"]").evaluateAll(elements=>elements.map(element=>({top:element.getBoundingClientRect().top,bottom:element.getBoundingClientRect().bottom})));assert.ok(primary.every(rect=>rect.top>=0&&rect.bottom<=844),"primary controls fit initial phone viewport");const dpad=await phone.locator(".cinema-dpad").evaluate(element=>({areas:getComputedStyle(element).gridTemplateAreas,targets:Array.from(element.querySelectorAll("button"),button=>({width:button.getBoundingClientRect().width,height:button.getBoundingClientRect().height}))}));assert.ok(dpad.areas.includes("left select right"));assert.ok(dpad.targets.every(rect=>rect.width>=44&&rect.height>=44));
    // Keep a legitimate fresh interaction credit, physically open a restricted
    // dialog, then send through the real authenticated API. No blind Select.
    await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER.state?.credits.some(value=>value.kind==="interaction"));
    const stale=await phone.evaluate(()=>{const c=CINEMA_WEB_CONTROLLER,s=c.state,k=c.sequenceKey(),sequence=c.sequences.get(k)+1;c.sequences.set(k,sequence);return {version:CinemaRemoteWire.version,target:c.device.target,grant_id:c.grant.grant_id,control_epoch:c.control.control_epoch,sequence,credit:s.credits.findLast(value=>value.kind==="interaction").nonce,context_revision:s.context_revision,focus_revision:s.focus_revision,action:{type:"select"}};});
    await tv.locator("#statsbtn").click();await tv.waitForFunction(()=>document.getElementById("statsov").classList.contains("on"));const before=await tv.evaluate(()=>({hash:location.hash,paused:document.getElementById("video").paused}));
    await phone.evaluate(async command=>{const c=CINEMA_WEB_CONTROLLER;try{await c.client.request("commands",{body:command,proof:c.proof()});}catch(error){if(!["stale_context","busy"].includes(error.code))throw error;}},stale);await phone.waitForTimeout(600);assert.deepEqual(await tv.evaluate(()=>({hash:location.hash,paused:document.getElementById("video").paused})),before);assert.equal(await tv.evaluate(()=>cinemaRemoteSafeState().route),"restricted");await tv.locator("#statsbtn").click();
    const retiredTarget=await phone.evaluate(()=>CinemaRemoteWire.targetKey(CINEMA_WEB_CONTROLLER.device.target));
    await tv.evaluate(()=>{CINEMA_WEB_RECEIVER.retire("owner_replaced",false);cinemaRemoteReceiverSync();});await tv.waitForFunction(old=>CINEMA_WEB_RECEIVER?.state==="available"&&CinemaRemoteWire.targetKey(CINEMA_WEB_RECEIVER.target)!==old,retiredTarget);await phone.waitForFunction(()=>!CINEMA_WEB_CONTROLLER.ownsControl());
    await phone.getByRole("button",{name:"Change screen",exact:true}).click();await phone.getByRole("button",{name:"B05 TV",exact:true}).click();await phone.getByRole("button",{name:"Use as remote",exact:true}).waitFor();assert.equal(await phone.evaluate(()=>CINEMA_WEB_CONTROLLER.ownsControl()),false);await phone.getByRole("button",{name:"Use as remote",exact:true}).click();await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER.ownsControl(),null,{timeout:5000}).catch(async error=>{console.log("reacquire",await phone.evaluate(()=>globalThis.b05UiTrace),await tv.evaluate(()=>({state:CINEMA_WEB_RECEIVER?.state,focused:document.hasFocus()})));throw error;});
    await phone.waitForFunction(()=>CINEMA_WEB_CONTROLLER.state?.route==="playback"&&CINEMA_WEB_CONTROLLER.state.credits.length>0,null,{timeout:5000}).catch(async error=>{console.log("replacement state",await tv.evaluate(()=>({receiver:CINEMA_WEB_RECEIVER.state,focus:document.hasFocus(),route:cinemaRemoteSafeState().route,stats:document.getElementById("statsov")?.className,guardActive:CINEMA_WEB_RECEIVER.guard.active,control:!!CINEMA_WEB_RECEIVER.control})),await phone.evaluate(()=>({message:CINEMA_WEB_CONTROLLER.message,route:CINEMA_WEB_CONTROLLER.state?.route,credits:CINEMA_WEB_CONTROLLER.state?.credits.length,owned:CINEMA_WEB_CONTROLLER.ownsControl()})));throw error;});await phone.getByRole("button",{name:"Play",exact:true}).click();await tv.waitForFunction(()=>!document.getElementById("video").paused);
    // The local owner pauses synchronously even with every API unavailable;
    // this bypasses no owner code and starts no second player.
    await tvContext.route("**/api/**",route=>route.abort());const offlineOutcome=await tv.evaluate(()=>{CinemaRemote.physicalInput();const outcome=CinemaRemote.dispatch({type:"set_playing",playing:false},{...CinemaRemote.snapshot(),source:"local_cec"});return {outcome,paused:document.getElementById("video").paused};});assert.deepEqual(offlineOutcome,{outcome:"applied",paused:true});assert.equal(await tv.evaluate(()=>{CinemaRemote.physicalInput();return CinemaRemote.dispatch({type:"stop"},{...CinemaRemote.snapshot(),source:"local_cec"});}),"applied");await tv.waitForFunction(()=>!WATCH&&!document.getElementById("modal").classList.contains("open"));await tvContext.unroute("**/api/**");
    // Revocation is real account-owned API state, and the old phone proof fails.
    const grantId=await phone.evaluate(()=>CINEMA_WEB_CONTROLLER.grant.grant_id);await tvRoute("#/settings/developer");await tv.bringToFront();await tv.locator("button[onclick=\"cinemaRemoteRevokeGrant('"+grantId+"',event)\"]").click();await phone.waitForFunction(()=>!CINEMA_WEB_CONTROLLER.ownsControl());
    const oldProof=await phone.evaluate(async()=>{const saved=cinemaRemoteLoad(cinemaRemoteIdentity()).grants[0],client=new CinemaRemoteClient();try{await client.request("control",{body:{target:CINEMA_REMOTE_SELECTED.target,grant_id:saved.grant_id,action:"acquire",control_epoch:null},proof:{kind:"grant",secret:saved.grant_secret}});return "accepted";}catch(error){return error.code;}finally{client.retire();}});assert.equal(oldProof,"unauthorized");
    // Administrator path uses the same safe management mount after its normal
    // privileged settings load; the TV/phone above remained ordinary viewers.
    if(fixture.admin_token){const admin=await phoneBrowser.newContext();await seed(admin,fixture.admin_token);const page=await admin.newPage();page.on("pageerror",error=>errors.push(error.message));await page.goto(fixture.base_url+"/#/settings/developer");await page.waitForFunction(()=>{const mount=document.getElementById("cinema-remote-management");return mount&&!mount.textContent.includes("Loading");});assert.ok(await page.locator("#dev-cinema-cec").count());await admin.close();}
    assert.deepEqual(errors,[]);console.log(JSON.stringify({live_remote:"PASS",api_source_revision:fixture.api_source_revision,api_source_sha256:fixture.api_source_sha256,web_source_revision:fixture.web_source_revision,web_source_sha256:fixture.web_source_sha256,manual_pairing:true,qr_canvas:true,late_pairing_fenced:true,real_owner_play_pause:true,restricted_dialog:true,offline_local_pause:true,offline_local_stop:true,owner_replacement:true,revoked_grant:grantId?true:false,phone_focus:"separate-device Playwright emulation",tv_focus:nativeTvFocus?"native headed Chromium noDefaults":"separate-device Playwright emulation"}));
  }finally{
    if(receiverId&&phone&&!phone.isClosed())await phone.evaluate(async id=>{const c=new CinemaRemoteClient();try{await c.request("receivers/"+id,{method:"DELETE"});}catch(_){}finally{c.retire();}},receiverId).catch(()=>{});
    await phoneContext.close();await phoneBrowser.close();await tvRuntime.close();
  }
});
