from __future__ import annotations

import importlib.machinery
import importlib.util
import subprocess
import tempfile
import tomllib
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SCRIPT = ROOT / "scripts/vendor-audit-lock"
REGISTRY = "registry+https://github.com/rust-lang/crates.io-index"


def load_script():
    loader = importlib.machinery.SourceFileLoader("vendor_audit_lock", str(SCRIPT))
    spec = importlib.util.spec_from_loader(loader.name, loader)
    module = importlib.util.module_from_spec(spec)
    loader.exec_module(module)
    return module


def lock_text(*blocks: str) -> str:
    return (
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 4\n\n" + "\n".join(blocks)
    )


def block(name: str, version: str, source: str | None = None) -> str:
    text = f'[[package]]\nname = "{name}"\nversion = "{version}"\n'
    if source is not None:
        text += f'source = "{source}"\nchecksum = "{"0" * 64}"\n'
    return text


def packages(path: Path) -> list[tuple[str, str, str]]:
    parsed = tomllib.loads(path.read_text(encoding="utf-8"))
    return [
        (
            str(package["name"]),
            str(package["version"]),
            str(package.get("source", "")),
        )
        for package in parsed["package"]
    ]


class VendorAuditLockCase(unittest.TestCase):
    def test_additional_lock_is_completely_deduplicated_into_one_inventory(self):
        with tempfile.TemporaryDirectory() as directory:
            temporary = Path(directory)
            root_only = temporary / "root.lock"
            combined = temporary / "combined.lock"
            subprocess.run(
                [str(SCRIPT), "--output", str(root_only)],
                cwd=ROOT,
                check=True,
            )
            subprocess.run(
                [
                    str(SCRIPT),
                    "--output",
                    str(combined),
                    "--additional-lock",
                    "fuzz/Cargo.lock",
                ],
                cwd=ROOT,
                check=True,
            )

            root_packages = set(packages(root_only))
            fuzz_packages = set(packages(ROOT / "fuzz/Cargo.lock"))
            combined_packages = packages(combined)

            self.assertEqual(set(combined_packages), root_packages | fuzz_packages)
            self.assertEqual(len(combined_packages), len(set(combined_packages)))
            self.assertIn(
                (
                    "libfuzzer-sys",
                    "0.4.13",
                    "registry+https://github.com/rust-lang/crates.io-index",
                ),
                combined_packages,
            )

    def test_additional_lock_path_copy_of_a_vendored_crate_is_dropped(self):
        """A second workspace's patched-in vendored crate is not merged twice.

        fuzz/parsers/ patches `dolby_vision` from vendor/ exactly as the root
        does, so its lock records a path-sourced `dolby_vision 3.4.0` while the
        synthesized root lock already carries that version with registry
        provenance. Merging both would put two blocks for one name and version
        in the inventory; the path copy is dropped, and everything else the
        additional lock brings — a new registry crate, the fuzz package itself
        — is kept.
        """
        script = load_script()
        primary = lock_text(
            block("anyhow", "1.0.104", REGISTRY),
            block("dolby_vision", "3.4.0", REGISTRY),
            block("plurx-core", "0.1.0"),
        )
        addition = lock_text(
            block("anyhow", "1.0.104", REGISTRY),
            block("dolby_vision", "3.4.0"),
            block("libfuzzer-sys", "0.4.13", REGISTRY),
            block("plurx-core", "0.1.0"),
            block("plurx-parser-fuzz", "0.0.0"),
        )

        merged = tomllib.loads(script.merge_package_inventories(primary, [addition]))
        identities = [
            (package["name"], package["version"], package.get("source", ""))
            for package in merged["package"]
        ]

        self.assertEqual(len(identities), len(set(identities)))
        self.assertEqual(
            [identity for identity in identities if identity[0] == "dolby_vision"],
            [("dolby_vision", "3.4.0", REGISTRY)],
        )
        self.assertIn(("libfuzzer-sys", "0.4.13", REGISTRY), identities)
        self.assertIn(("plurx-parser-fuzz", "0.0.0", ""), identities)
        self.assertEqual(
            sorted(identities),
            sorted(
                [
                    ("anyhow", "1.0.104", REGISTRY),
                    ("dolby_vision", "3.4.0", REGISTRY),
                    ("libfuzzer-sys", "0.4.13", REGISTRY),
                    ("plurx-core", "0.1.0", ""),
                    ("plurx-parser-fuzz", "0.0.0", ""),
                ]
            ),
        )


if __name__ == "__main__":
    unittest.main()
